// <auto-generated />
namespace NtpProje_Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Create_SP_CategoryReport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_SP_CategoryReport));
        
        string IMigrationMetadata.Id
        {
            get { return "202511211206566_Create_SP_CategoryReport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
